### ISSUE TITLE
More Attributes needed 

### ISSUE THREAD

**Issue by Francesco146** [b-ryu/yt-mp3-dl#1]
Error: ord() expected string of length 1, but int found

Error found on eyeD3.load(), in yt_metadata.py

Fixed with libmagic and eyeD3 v0.7.11

**Comment by Francesco146** [comment]
input/song.mp3
song.json (well formatted)

errors everywhere

**Comment by Francesco146** [comment]
i know where the error is, is in the eyed3.load(), seams to not working anymore

**Comment by b-ryu** [comment]
Hey @Francesco146, thanks for opening an issue. It's been a while since I've touched this project.

Could you be a bit more specific in which script you're trying to use (`yt-mp3-dl`, `yt-metadata`, or `yt-dl-metadata`)?
I did come across an issue when trying to use `yt-metadata`, but I found that installing `libmagic` fixed issues with the [`eyeD3` dependency](https://stackoverflow.com/questions/46518690/pip-installing-eyed3-module-failed-to-find-libmagic).

Please note that I've only tested this on my own Mac machine.

**Comment by Francesco146** [comment]
Ok, so... I figured out that I had to install libmagic, and eyeD3 version 0.7.11, now it actually works, but if the json has a lot of information it tends to put only a few, I always think it is the bad library eyeD3, can you confirm?

**Comment by b-ryu** [comment]
Sure, though I'm on the latest version `0.9.5`. Could you describe what you mean "put only a few"? Is it skipping files or attributes?

**Comment by Francesco146** [comment]
Yeah, i mean few attributes, never tested multi files. 
Like:
Description
Year

**Comment by Francesco146** [comment]
I have the impression that only takes few ot the attributes of the json, the program seems to not reading all the json


ok, i think i found the problem.

`    apply_metadata_tag(mp3_file, 'artist', data)`
`    apply_metadata_tag(mp3_file, 'title', data)`
`    apply_metadata_tag(mp3_file, 'album', data)`
`    apply_metadata_tag(mp3_file, 'album_artist', data, 'artist')`

**Comment by Francesco146** [comment]
``

**Comment by b-ryu** [comment]
Yes, I believe right now it only supports [a handful of attributes](https://github.com/b-ryu/yt-mp3-dl/blob/f1c57d70f900711fa525122e19b193b438a0f97b/yt_metadata.py#L165).

**Comment by Francesco146** [comment]
yeah, i'll leave this issue open, hope you get to work, have a nice day 🥇
